@startuml
'https://plantuml.com/class-diagram


class EventRegistryEngineConfigurator
{
    EventRegistryEngine eventRegistryEngine;
    EventRegistryEngineConfiguration eventEngineConfiguration
    void configure(AbstractEngineConfiguration engineConfiguration)
}
abstract class AbstractEngineConfigurator
{
void beforeInit(AbstractEngineConfiguration engineConfiguration)
void initialiseCommonProperties(AbstractEngineConfiguration engineConfiguration, AbstractEngineConfiguration targetEngineConfiguration)
}

interface EngineConfigurator

EngineConfigurator <|-- AbstractEngineConfigurator
AbstractEngineConfigurator <|-- EventRegistryEngineConfigurator

@enduml